<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <parent>
        <artifactId>lutece-global-pom</artifactId>
        <groupId>fr.paris.lutece.tools</groupId>
        <version>8.0.0-SNAPSHOT</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <groupId>fr.paris.lutece.plugins</groupId>

    <artifactId>module-forms-cartography-explorer</artifactId>
    <packaging>lutece-plugin</packaging>
    
    <version>2.0.0-SNAPSHOT</version>
    <name>Lutece forms cartography explorer module</name>

    <repositories>
        <repository>
            <id>lutece</id>
            <name>luteceRepository</name>
            <url>https://dev.lutece.paris.fr/maven_repository</url>
            <layout>default</layout>
        </repository>
        <repository>
            <id>luteceSnapshot</id>
            <name>luteceSnapshot</name>
            <url>https://dev.lutece.paris.fr/snapshot_repository</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
            <releases>
                <enabled>false</enabled>
            </releases>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>fr.paris.lutece</groupId>
            <artifactId>lutece-core</artifactId>
            <version>[8.0.0-SNAPSHOT,)</version>
            <type>lutece-core</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>module-cartography-solr</artifactId>
            <version>[2.0.0-SNAPSHOT,)</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-forms</artifactId>
            <version>[4.0.0-SNAPSHOT,)</version>
            <type>lutece-plugin</type>
        </dependency>
        <!-- JUnit -->
		<dependency>
		    <groupId>fr.paris.lutece.plugins</groupId>
		    <artifactId>library-lutece-unit-testing</artifactId>
		    <type>jar</type>
		    <scope>test</scope>
		    <!--Jetty dependencies are excluded to force the retrieval of those returned by the module-cartography-solr artefact. 
		        Those from library-lutece-unit-testing cause ClassNotFoundException when using the module because their version 
		        is older than that of the module-cartography-solr artefact and therefore doesn't have certain classes.-->
		    <exclusions>
                <exclusion>
                    <groupId>org.eclipse.jetty</groupId>
                    <artifactId>jetty-io</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.eclipse.jetty</groupId>
                    <artifactId>jetty-util</artifactId>
                </exclusion>
                 <exclusion>
                    <groupId>org.eclipse.jetty</groupId>
                    <artifactId>jetty-http</artifactId>
                </exclusion>
            </exclusions>		
		</dependency>
		<dependency>
			<groupId>org.glassfish.jaxb</groupId>
	        <artifactId>jaxb-runtime</artifactId>
	        <scope>test</scope>  
		</dependency>
		<dependency>
			<groupId>org.hibernate.validator</groupId>
	        <artifactId>hibernate-validator</artifactId>
	        <scope>test</scope>  
		</dependency>
		<dependency>
			<groupId>org.glassfish</groupId>
	        <artifactId>jakarta.el</artifactId>
	        <scope>test</scope>  
		</dependency>
    </dependencies>

    <properties>
        <componentName>forms cartography explorer</componentName>
    </properties>
</project>
